-- Create database if not exists
CREATE DATABASE IF NOT EXISTS FINANCE_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.GOLD;

-- Create bronze layer table
CREATE OR REPLACE TABLE FINANCE_DB.RAW.STOCK_PRICES (
    TRADING_DATE DATE NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    OPEN_PRICE FLOAT NOT NULL,
    HIGH_PRICE FLOAT NOT NULL,
    LOW_PRICE FLOAT NOT NULL,
    CLOSE_PRICE FLOAT NOT NULL,
    VOLUME BIGINT NOT NULL,
    ADJUSTED_CLOSE FLOAT,
    DOWNLOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    FILE_NAME VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Metadata columns for data governance
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'YAHOO_FINANCE',
    BATCH_ID VARCHAR(50),
    
    -- Primary key
    PRIMARY KEY (TRADING_DATE, TICKER)
);

-- Create stream for CDC
CREATE OR REPLACE STREAM RAW.STOCK_PRICES_STREAM ON TABLE RAW.STOCK_PRICES;